name: ContainerGuard Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Docker security scan
        run: python3 scanner.py

      - name: Run Kubernetes security scan
        run: python3 k8s_scanner.py

      - name: Save reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: containerguard-reports
          path: |
            containerguard_report.html
            containerguard_report.json
            deployment_report.html
            k8s_report.json